POST https://global-api-sandbox.afterpay.com/v2/checkouts
Authorization: Basic MTAwMjA1NjMxOjdhMjRmMDJjM2JjZGU1MmU1ZDM4NGNmNzBhMjcwZGU2NmYxYjNlYTQ5M2IwOGIyOTRhZjZiZjA3OTJiNDhkMjE2MGNkZTkyZTU4ZGEzMjk2YWExMzQ4YzlmNjRjNWI2Njk4OWYwMjFhMTVhNDMxZWI2M2MzZjBhNzE0ZWMzYzE1
Content-Type: application/json
User-Agent: Merchantname/100205631

{
  "amount": {
    "amount": "100.00",
    "currency": "USD"
  },
  "consumer": {
    "email": "test@example.com",
    "givenNames": "Joe",
    "surname": "Consumer",
    "phoneNumber": "0400 000 000"
  },
  "merchantReference": "string",
  "merchant": {
    "redirectConfirmUrl": "https://example.com/checkout/confirm",
    "redirectCancelUrl": "https://example.com/checkout/cancel",
    "name": "string"
  }
}

GET https://global-api-sandbox.afterpay.com/v2/configuration 
Authorization: Basic e53823db7500ef69372c5f9fd54911590f599dec42dadc4ac07c49a26751afb50a653c382b07a9e41f86bb08406e94ccc8ecbf978d30bca84d899798d8521f4
Content-Type: application/json
User-Agent: Merchantname/109361138


{
  "token": "002.ld8kv7dtnpgh0fbfef0u21liebiqkjh92r2a1ngugppai4b6",
  "expires": "2024-08-16T12:45:41.153Z",
  "redirectCheckoutUrl": "https://portal.sandbox.afterpay.com/us/checkout/?token=002.ld8kv7dtnpgh0fbfef0u21liebiqkjh92r2a1ngugppai4b6"
}

https://example.com/checkout/confirm?&status=SUCCESS&orderToken=002.ld8kv7dtnpgh0fbfef0u21liebiqkjh92r2a1ngugppai4b6

POST https://global-api-sandbox.afterpay.com/v2/payments/capture
Authorization: Basic MTAwMjA1NjMxOjdhMjRmMDJjM2JjZGU1MmU1ZDM4NGNmNzBhMjcwZGU2NmYxYjNlYTQ5M2IwOGIyOTRhZjZiZjA3OTJiNDhkMjE2MGNkZTkyZTU4ZGEzMjk2YWExMzQ4YzlmNjRjNWI2Njk4OWYwMjFhMTVhNDMxZWI2M2MzZjBhNzE0ZWMzYzE1
Content-Type: application/json

{
  "token":"002.ld8kv7dtnpgh0fbfef0u21liebiqkjh92r2a1ngugppai4b6"
}

GET https://global-api-sandbox.afterpay.com/v2/payments/002.sl2p0c7leg6n5cvomtujsgk1k77ocoqdiqf8ibsnh7tspkpk
Authorization: Basic MTAwMjA1NjMxOjdhMjRmMDJjM2JjZGU1MmU1ZDM4NGNmNzBhMjcwZGU2NmYxYjNlYTQ5M2IwOGIyOTRhZjZiZjA3OTJiNDhkMjE2MGNkZTkyZTU4ZGEzMjk2YWExMzQ4YzlmNjRjNWI2Njk4OWYwMjFhMTVhNDMxZWI2M2MzZjBhNzE0ZWMzYzE1
Content-Type: application/json
