name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  install:
    uses: ./.github/workflows/_install.yml
    with:
      node-version: "20"

  lint:
    needs: [install]
    uses: ./.github/workflows/_lint.yml
    with:
      node-version: "20"

  test:
    needs: [install]
    uses: ./.github/workflows/_test.yml
    with:
      node-version: "20"

  build:
    needs: [lint, test]
    uses: ./.github/workflows/_build.yml
    with:
      node-version: "20"
