/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */
import type { PickUserExcludeKeyofUserDobOrGenderOrWpOrDealerId } from './pickUserExcludeKeyofUserDobOrGenderOrWpOrDealerId';
import type { AddressAllOf } from './addressAllOf';

export type Address = PickUserExcludeKeyofUserDobOrGenderOrWpOrDealerId & AddressAllOf;
