/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */
import type { USStateCode } from './uSStateCode';

export type AddressAllOf = {
	address: string;
	address2?: string;
	city: string;
	postcode: string;
	stateCode: USStateCode;
};
