/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */
import type { BookingDotComFlightOfferResponse } from './bookingDotComFlightOfferResponse';

export interface BookingDotComFlightResponse {
    flightOffers: BookingDotComFlightOfferResponse[];
    [key: string]: unknown;
}
