/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */

export type CabinClass = (typeof CabinClass)[keyof typeof CabinClass];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CabinClass = {
    ECONOMY: 'ECONOMY',
    PREMIUM_ECONOMY: 'PREMIUM_ECONOMY',
    BUSINESS: 'BUSINESS',
    FIRST: 'FIRST',
} as const;
