/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */

export type CabinClass = (typeof CabinClass)[keyof typeof CabinClass];

 
export const CabinClass = {
	ECONOMY: 'ECONOMY',
	PREMIUM_ECONOMY: 'PREMIUM_ECONOMY',
	BUSINESS: 'BUSINESS',
	FIRST: 'FIRST',
} as const;
