/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

/**
 */
export type ChoiceRequestAnyOfType =
    (typeof ChoiceRequestAnyOfType)[keyof typeof ChoiceRequestAnyOfType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChoiceRequestAnyOfType = {
    intent: 'intent',
} as const;
