/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { ChoiceResponsePayload } from './choiceResponsePayload';
import type { ChoiceResponseType } from './choiceResponseType';

export interface ChoiceResponse {
    payload: ChoiceResponsePayload;
    time: number;
    /** */
    type: ChoiceResponseType;
}
