/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

/**
 */
export type ChoiceResponseType = (typeof ChoiceResponseType)[keyof typeof ChoiceResponseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChoiceResponseType = {
    choice: 'choice',
} as const;
