/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { CreateParent200StudentsItem } from './createParent200StudentsItem';
import type { CreateParent200Type } from './createParent200Type';

export type CreateParent200 = {
    email: string;
    id: string;
    name: string;
    pamId?: string;
    password: string;
    phone: string;
    students: CreateParent200StudentsItem[];
    surname: string;
    type: CreateParent200Type;
};
