/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { CreateStudent200StudentsItemGender } from './createStudent200StudentsItemGender';

export type CreateStudent200StudentsItem = {
    date_of_birth: string;
    gender: CreateStudent200StudentsItemGender;
    grade: number;
    id: string;
    name: string;
    surname: string;
    teacher_id: string;
};
