/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

export type CreateStudent200StudentsItemGender =
    (typeof CreateStudent200StudentsItemGender)[keyof typeof CreateStudent200StudentsItemGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateStudent200StudentsItemGender = {
    Male: 'Male',
    Female: 'Female',
} as const;
