/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

export type CreateParent200StudentsItemGender =
    (typeof CreateParent200StudentsItemGender)[keyof typeof CreateParent200StudentsItemGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateParent200StudentsItemGender = {
    Male: 'Male',
    Female: 'Female',
} as const;
