/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */

export interface CreateSyncAppointmentRequest {
	endTime: string;
	memberId: number;
	startDate: string;
	startTime: string;
}
