/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

export type CreateStudent200Type = (typeof CreateStudent200Type)[keyof typeof CreateStudent200Type];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateStudent200Type = {
    admin: 'admin',
    parent: 'parent',
} as const;
