/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

export type CreateParent200Type = (typeof CreateParent200Type)[keyof typeof CreateParent200Type];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateParent200Type = {
    admin: 'admin',
    parent: 'parent',
} as const;
