/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { CreateParent200StudentsItemGender } from './createParent200StudentsItemGender';

export type CreateParent200StudentsItem = {
    date_of_birth: string;
    gender: CreateParent200StudentsItemGender;
    grade: number;
    id: string;
    name: string;
    surname: string;
    teacher_id: string;
};
