/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */
import type { ProductId } from './productId';

export type CreateAdHocOrderInstallmentParams = {
	email: string;
	amount: number;
	productId: ProductId;
	key: string;
};
