/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

export type DeleteStudent200Type = (typeof DeleteStudent200Type)[keyof typeof DeleteStudent200Type];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteStudent200Type = {
    admin: 'admin',
    parent: 'parent',
} as const;
