/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

export type DeleteStudent200StudentsItemGender =
    (typeof DeleteStudent200StudentsItemGender)[keyof typeof DeleteStudent200StudentsItemGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteStudent200StudentsItemGender = {
    Male: 'Male',
    Female: 'Female',
} as const;
