/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { DeleteStudent200StudentsItem } from './deleteStudent200StudentsItem';
import type { DeleteStudent200Type } from './deleteStudent200Type';

export type DeleteStudent200 = {
    email: string;
    id: string;
    name: string;
    pamId?: string;
    password: string;
    phone: string;
    students: DeleteStudent200StudentsItem[];
    surname: string;
    type: DeleteStudent200Type;
};
