/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { DeleteStudent200StudentsItemGender } from './deleteStudent200StudentsItemGender';

export type DeleteStudent200StudentsItem = {
    date_of_birth: string;
    gender: DeleteStudent200StudentsItemGender;
    grade: number;
    id: string;
    name: string;
    surname: string;
    teacher_id: string;
};
