/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */

export type FlightType = (typeof FlightType)[keyof typeof FlightType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FlightType = {
    ROUNDTRIP: 'ROUNDTRIP',
    ONEWAY: 'ONEWAY',
    MULTISTOP: 'MULTISTOP',
} as const;
