/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { Message } from './message';
import type { ObjectId } from './objectId';

export type GetChat200 = {
    created_at: string;
    id: string;
    messages: Message[];
    user_id: ObjectId;
};
