/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

export type GetChat200Parent = {
    email: string;
    id: string;
    name: string;
    phone: string;
    surname: string;
};
