/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { GetChat200StartupVariablesParent } from './getChat200StartupVariablesParent';
import type { Student } from './student';

export type GetChat200StartupVariables = {
    api_token: string;
    debug_ind: number;
    parent: GetChat200StartupVariablesParent;
    students: Student[];
};
