/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { GetChat200Chat } from './getChat200Chat';
import type { GetChat200StartupVariables } from './getChat200StartupVariables';

export type GetChat200 = {
    chat: GetChat200Chat;
    startupVariables: GetChat200StartupVariables;
};
