/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */

export type GetFlightBookingUrlParams = {
	from: string;
	to: string;
	token: string;
};
