/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */
import type { FlightType } from './flightType';
import type { CabinClass } from './cabinClass';
import type { SortingCategory } from './sortingCategory';

export type GetFlightOffersParams = {
    type: FlightType;
    cabinClass: CabinClass;
    adults: number;
    sort: SortingCategory;
    from: string;
    to: string;
    departDate: string;
    returnDate?: string;
    children?: string;
    multiStopDates?: string;
    salesCountry?: string;
};
