/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

export type GetParents200ItemStudentsItemGender =
    (typeof GetParents200ItemStudentsItemGender)[keyof typeof GetParents200ItemStudentsItemGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetParents200ItemStudentsItemGender = {
    Male: 'Male',
    Female: 'Female',
} as const;
