/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

export type GetParents200ItemType =
    (typeof GetParents200ItemType)[keyof typeof GetParents200ItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetParents200ItemType = {
    admin: 'admin',
    parent: 'parent',
} as const;
