/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { IntentPayloadIntent } from './intentPayloadIntent';

/**
 * Generic payloads
 */
export interface IntentPayload {
    actions: unknown[];
    entities: unknown[];
    intent: IntentPayloadIntent;
    label: string;
    query: string;
}
