/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */
import type { ListGetResponseCompulsory } from './listGetResponseCompulsory';
import type { ObjectId } from './objectId';

export interface ListGetResponse {
    compulsory: ListGetResponseCompulsory;
    id: ObjectId;
    optional: unknown;
}
