/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */
import type { ListItem } from './listItem';

export type ListPostRequestCompulsory = {
    items: ListItem[];
    list_name: string;
    [key: string]: unknown;
};
