/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */
import type { ListItemPriority } from './listItemPriority';

export interface ListItem {
	deadline_date?: string;
	end_date?: string;
	is_complete: boolean;
	item_name: string;
	notes?: string;
	priority?: ListItemPriority;
	recurrence?: string;
	recurrence_cron?: string;
	reminder_date?: string;
	status?: string;
	[key: string]: unknown;
}
