/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */
import type { ListItem } from './listItem';

export type ListGetResponseCompulsory = {
    items: ListItem[];
    list_name: string;
    [key: string]: unknown;
};
