/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */

export type ListItemPriority = (typeof ListItemPriority)[keyof typeof ListItemPriority];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListItemPriority = {
    high: 'high',
    medium: 'medium',
    low: 'low',
} as const;
