/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { SuccessRequest } from './successRequest';
import type { FailRequest } from './failRequest';

export type LocationRequestResponsePathsItemEvent = SuccessRequest | FailRequest;
