/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

/**
 */
export type LocationRequestResponseType =
    (typeof LocationRequestResponseType)[keyof typeof LocationRequestResponseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LocationRequestResponseType = {
    location_request: 'location_request',
} as const;
