/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */

/**
 * A class representation of the BSON ObjectId type.
 */
export type ObjectId = string;
