/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

/**
 * A class representation of the BSON ObjectId type.
 */
export type ObjectId = string;
