/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */
import type { PickUserExcludeKeyofUserDobOrGenderOrWpOrDealerId } from './pickUserExcludeKeyofUserDobOrGenderOrWpOrDealerId';

/**
 * Construct a type with the properties of T except for those in type K.
 */
export type OmitUserDobOrGenderOrWpOrDealerId = PickUserExcludeKeyofUserDobOrGenderOrWpOrDealerId;
