/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { PickEmbeddingExcludeKeyofEmbeddingId } from './pickEmbeddingExcludeKeyofEmbeddingId';

/**
 * Construct a type with the properties of T except for those in type K.
 */
export type OmitEmbeddingId = PickEmbeddingExcludeKeyofEmbeddingId;
