/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */
import type { PickEmbeddingFileExcludeKeyofEmbeddingFileTextOrUserId } from './pickEmbeddingFileExcludeKeyofEmbeddingFileTextOrUserId';

/**
 * Construct a type with the properties of T except for those in type K.
 */
export type OmitEmbeddingFileTextOrUserId = PickEmbeddingFileExcludeKeyofEmbeddingFileTextOrUserId;
