/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */
import type { PersonalInfo } from './personalInfo';
import type { OrderDetailsAllOf } from './orderDetailsAllOf';

export type OrderDetails = PersonalInfo & OrderDetailsAllOf;
