/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */
import type { Product } from './product';

export type OrderInstallmentDetailsAllOf = {
	amount: number;
	installmentIndex: number;
	product: Product;
};
