/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */

export interface ParsedFormidableUser {
	address: string;
	address2: string;
	brand_id: string;
	city: string;
	dealer_id: string;
	dob: string;
	email: string;
	first_name: string;
	gender: string;
	id: string;
	last_name: string;
	middle_name: string;
	phone: string;
	postcode: string;
	sponsor_id: string;
	state: string;
	stateCode: string;
}
