/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */
import type { Address } from './address';
import type { User } from './user';

export interface PersonalInfo {
	billing: Address;
	shipping: Address;
	user: User;
}
