/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export interface PickPrescriberyPaymentRequestExcludeKeyofPrescriberyPaymentRequestAssessmentTokenOrPlanOrBillingOrShipping {
	assessment_id?: number;
	dob: string;
	email: string;
	first_name: string;
	gender: string;
	isSyncUpgrade?: boolean;
	last_name: string;
	lead_id?: number;
	patient_id?: string;
	redirect_url: string;
}
