/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export interface PickUserExcludeKeyofUserDobOrGenderOrWpOrDealerId {
	email: string;
	firstName: string;
	lastName: string;
	middleName?: string;
	phone: string;
}
