/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { ObjectId } from './objectId';

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export interface PickEmbeddingExcludeKeyofEmbeddingId {
    is_pending?: boolean;
    pam_id: string;
    summary?: string;
    user_id: ObjectId;
}
