/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */

export type PrescriberyReassessmentMedication =
	(typeof PrescriberyReassessmentMedication)[keyof typeof PrescriberyReassessmentMedication];

 
export const PrescriberyReassessmentMedication = {
	Semaglutide_Tier_1_Increase_my_dose: 'Semaglutide_Tier_1_Increase_my_dose',
	Semaglutide_Tier_1_Stay_on_my_current_dose: 'Semaglutide_Tier_1_Stay_on_my_current_dose',
	Semaglutide_Tier_1_Switch_to_Tirzepatide: 'Semaglutide_Tier_1_Switch_to_Tirzepatide',
	Semaglutide_Tier_2_Increase_my_dose: 'Semaglutide_Tier_2_Increase_my_dose',
	Semaglutide_Tier_2_Stay_on_my_current_dose: 'Semaglutide_Tier_2_Stay_on_my_current_dose',
	Semaglutide_Tier_2_Decrease_my_dose: 'Semaglutide_Tier_2_Decrease_my_dose',
	Semaglutide_Tier_2_Switch_to_Tirzepatide: 'Semaglutide_Tier_2_Switch_to_Tirzepatide',
	Semaglutide_Tier_3_Stay_on_my_current_dose: 'Semaglutide_Tier_3_Stay_on_my_current_dose',
	Semaglutide_Tier_3_Decrease_my_dose: 'Semaglutide_Tier_3_Decrease_my_dose',
	Semaglutide_Tier_3_Switch_to_Tirzepatide: 'Semaglutide_Tier_3_Switch_to_Tirzepatide',
	Tirzepatide_Tier_1_Increase_my_dose: 'Tirzepatide_Tier_1_Increase_my_dose',
	Tirzepatide_Tier_1_Stay_on_my_current_dose: 'Tirzepatide_Tier_1_Stay_on_my_current_dose',
	Tirzepatide_Tier_1_Switch_to_Semaglutide: 'Tirzepatide_Tier_1_Switch_to_Semaglutide',
	Tirzepatide_Tier_2_Increase_my_dose: 'Tirzepatide_Tier_2_Increase_my_dose',
	Tirzepatide_Tier_2_Stay_on_my_current_dose: 'Tirzepatide_Tier_2_Stay_on_my_current_dose',
	Tirzepatide_Tier_2_Decrease_my_dose: 'Tirzepatide_Tier_2_Decrease_my_dose',
	Tirzepatide_Tier_2_Switch_to_Semaglutide: 'Tirzepatide_Tier_2_Switch_to_Semaglutide',
	Tirzepatide_Tier_3_Stay_on_my_current_dose: 'Tirzepatide_Tier_3_Stay_on_my_current_dose',
	Tirzepatide_Tier_3_Decrease_my_dose: 'Tirzepatide_Tier_3_Decrease_my_dose',
	Tirzepatide_Tier_3_Switch_to_Semaglutide: 'Tirzepatide_Tier_3_Switch_to_Semaglutide',
} as const;
