/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */
import type { PickPrescriberyPaymentRequestExcludeKeyofPrescriberyPaymentRequestAssessmentTokenOrPlanOrBillingOrShipping } from './pickPrescriberyPaymentRequestExcludeKeyofPrescriberyPaymentRequestAssessmentTokenOrPlanOrBillingOrShipping';
import type { PrescriberyReassessmentPaymentRequestAllOf } from './prescriberyReassessmentPaymentRequestAllOf';

export type PrescriberyReassessmentPaymentRequest =
	PickPrescriberyPaymentRequestExcludeKeyofPrescriberyPaymentRequestAssessmentTokenOrPlanOrBillingOrShipping &
		PrescriberyReassessmentPaymentRequestAllOf;
