/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */

/**
 */
export type ProductAllOfType = (typeof ProductAllOfType)[keyof typeof ProductAllOfType];

 
export const ProductAllOfType = {
	medication: 'medication',
} as const;
