/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */

export interface ProductPricing {
	psvAmount: number;
	/** Price per month supply. */
	retailPrice: number;
	uplineVolume: number;
	wholesalePrice: number;
}
