/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */

export type ProductId = (typeof ProductId)[keyof typeof ProductId];

 
export const ProductId = {
	semaglutide_tier_1: 'semaglutide_tier_1',
	semaglutide_tier_2: 'semaglutide_tier_2',
	semaglutide_tier_3: 'semaglutide_tier_3',
	tirzepatide_tier_1: 'tirzepatide_tier_1',
	tirzepatide_tier_2: 'tirzepatide_tier_2',
	tirzepatide_tier_3: 'tirzepatide_tier_3',
	b12: 'b12',
	nad_injection: 'nad_injection',
	nad_nasal_spray: 'nad_nasal_spray',
	sermorelin: 'sermorelin',
	synapsin: 'synapsin',
	pt_141_injection: 'pt_141_injection',
	pt_141_nasal_spray: 'pt_141_nasal_spray',
	semaglutide_sublingual_tier_1: 'semaglutide_sublingual_tier_1',
	semaglutide_sublingual_tier_2: 'semaglutide_sublingual_tier_2',
	semaglutide_sublingual_tier_3: 'semaglutide_sublingual_tier_3',
	sermorelin_tablets: 'sermorelin_tablets',
} as const;
