/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */
import type { ProductId } from './productId';
import type { TrinityProduct } from './trinityProduct';
import type { ProductAllOfType } from './productAllOfType';

export type ProductAllOf = {
	id: ProductId;
	/** ex: 3 means a 3 month supply */
	monthSupply: number;
	name: string;
	/** Optional. If not present, the product is not available for installment payments.  Each number represents a month. */
	payOverTimePlan?: number[];
	prescriberySource?: string;
	/** Used by Prescribery */
	prescriberyTemplate?: string;
	/** Used by WP */
	sku?: string;
	tier?: number;
	/** Used by Trinity */
	trinityId?: TrinityProduct;
	/** */
	type: ProductAllOfType;
	/** Image URL. */
	url: string;
};
