/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */
import type { QueryEmbeddingsById200EmbeddingsItem } from './queryEmbeddingsById200EmbeddingsItem';

export type QueryEmbeddingsById200 = {
	embeddings: QueryEmbeddingsById200EmbeddingsItem[];
	result: string;
};
