/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */

export type QueryEmbeddingsById200EmbeddingsItem = {
    score: number;
    text: string;
};
