/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */
import type { QueryEmbeddings200EmbeddingsItem } from './queryEmbeddings200EmbeddingsItem';

export type QueryEmbeddings200 = {
    embeddings: QueryEmbeddings200EmbeddingsItem[];
    result: string;
};
