/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */
import type { RecordStringString } from './recordStringString';

export interface QuestionnaireRequest {
	answers: RecordStringString[];
	email: string;
	entry: string;
	id_document?: string;
	product: string;
}
