/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */

export type ReassessmentToMedication =
	(typeof ReassessmentToMedication)[keyof typeof ReassessmentToMedication];

 
export const ReassessmentToMedication = {
	Semaglutide_Tier_2: 'Semaglutide_Tier_2',
	Semaglutide_Tier_3: 'Semaglutide_Tier_3',
	Semaglutide_Sublingual_Tier_2: 'Semaglutide_Sublingual_Tier_2',
	Semaglutide_Sublingual_Tier_3: 'Semaglutide_Sublingual_Tier_3',
	Tirzepatide_Tier_2: 'Tirzepatide_Tier_2',
	Tirzepatide_Tier_3: 'Tirzepatide_Tier_3',
} as const;
