/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */
import type { AvailableSlot } from './availableSlot';

/**
 * Construct a type with a set of properties K of type T
 */
export interface RecordStringAvailableSlotArray {
	[key: string]: AvailableSlot[];
}
