/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */
import type { ReminderGetResponseCompulsoryCondition } from './reminderGetResponseCompulsoryCondition';
import type { ReminderType } from './reminderType';

export type ReminderGetResponseCompulsory = {
    condition: ReminderGetResponseCompulsoryCondition;
    title: string;
    type: ReminderType;
    [key: string]: unknown;
};
