/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */
import type { ReminderPostRequestCompulsory } from './reminderPostRequestCompulsory';

export interface ReminderPostRequest {
    compulsory: ReminderPostRequestCompulsory;
    optional: unknown;
}
