/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */

export type ReminderType = (typeof ReminderType)[keyof typeof ReminderType];

 
export const ReminderType = {
	general: 'general',
	datetime: 'datetime',
	event: 'event',
	weather: 'weather',
} as const;
