/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */
import type { ReminderGetResponseCompulsory } from './reminderGetResponseCompulsory';
import type { ObjectId } from './objectId';

export interface ReminderGetResponse {
	compulsory: ReminderGetResponseCompulsory;
	created_at: string;
	id: ObjectId;
	is_deleted: boolean;
	optional: unknown;
	updated_at?: string;
	user_id: ObjectId;
}
