/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */
import type { ReminderPostRequestCompulsoryCondition } from './reminderPostRequestCompulsoryCondition';
import type { ReminderType } from './reminderType';

export type ReminderPostRequestCompulsory = {
    condition: ReminderPostRequestCompulsoryCondition;
    title: string;
    type: ReminderType;
    [key: string]: unknown;
};
