/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { ChoiceRequest } from './choiceRequest';
import type { TextRequest } from './textRequest';

export type SendMessageRequest = ChoiceRequest | TextRequest;
