/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { SetEmbeddedStatusStatus } from './setEmbeddedStatusStatus';

export interface SetEmbeddedStatus {
    id: string;
    /** */
    status: SetEmbeddedStatusStatus;
}
