/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

/**
 */
export type SetEmbeddedStatusStatus =
    (typeof SetEmbeddedStatusStatus)[keyof typeof SetEmbeddedStatusStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SetEmbeddedStatusStatus = {
    embedded: 'embedded',
} as const;
