/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */

export type SortingCategory = (typeof SortingCategory)[keyof typeof SortingCategory];

 
export const SortingCategory = {
	BEST: 'BEST',
	CHEAPEST: 'CHEAPEST',
	FASTEST: 'FASTEST',
} as const;
