/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

export type StudentGender = (typeof StudentGender)[keyof typeof StudentGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StudentGender = {
    Male: 'Male',
    Female: 'Female',
} as const;
