/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { SuccessRequestType } from './successRequestType';

export interface SuccessRequest {
    payload?: unknown;
    /** */
    type: SuccessRequestType;
}
