/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

/**
 */
export type SuccessRequestType = (typeof SuccessRequestType)[keyof typeof SuccessRequestType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SuccessRequestType = {
    success: 'success',
} as const;
