/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

/**
 */
export type TextRequestType = (typeof TextRequestType)[keyof typeof TextRequestType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TextRequestType = {
    text: 'text',
} as const;
