/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { TextResponsePayloadSlateContentItem } from './textResponsePayloadSlateContentItem';

export type TextResponsePayloadSlate = {
    content: TextResponsePayloadSlateContentItem[];
    id: string;
    messageDelayMilliseconds: number;
};
