/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

/**
 */
export type TextResponseType = (typeof TextResponseType)[keyof typeof TextResponseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TextResponseType = {
    text: 'text',
} as const;
