/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { TextResponsePayloadSlate } from './textResponsePayloadSlate';

export type TextResponsePayload = {
    delay?: number;
    message: string;
    slate?: TextResponsePayloadSlate;
};
