/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { TextResponsePayload } from './textResponsePayload';
import type { TextResponseType } from './textResponseType';

/**
 * Responses
 */
export interface TextResponse {
    payload: TextResponsePayload;
    time?: number;
    /** */
    type: TextResponseType;
}
