/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */

export type TrinityProduct = (typeof TrinityProduct)[keyof typeof TrinityProduct];

 
export const TrinityProduct = {
	Product_1: 'Product 1',
	Product_2: 'Product 2',
	Product_3: 'Product 3',
	Product_4: 'Product 4',
	Product_5: 'Product 5',
	Product_6: 'Product 6',
	Product_7: 'Product 7',
	Product_9: 'Product 9',
	Product_10: 'Product 10',
	Product_11: 'Product 11',
	Product_12: 'Product 12',
	Product_13: 'Product 13',
	Product_14: 'Product 14',
	Product_15: 'Product 15',
	Product_16: 'Product 16',
	Product_17: 'Product 17',
	Product_22: 'Product 22',
	Product_23: 'Product 23',
	Product_24: 'Product 24',
} as const;
