/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

export type UpdateParent200StudentsItemGender =
    (typeof UpdateParent200StudentsItemGender)[keyof typeof UpdateParent200StudentsItemGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateParent200StudentsItemGender = {
    Male: 'Male',
    Female: 'Female',
} as const;
