/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

export type UpdateStudent200Type = (typeof UpdateStudent200Type)[keyof typeof UpdateStudent200Type];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateStudent200Type = {
    admin: 'admin',
    parent: 'parent',
} as const;
