/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

export type UpdateStudent200StudentsItemGender =
    (typeof UpdateStudent200StudentsItemGender)[keyof typeof UpdateStudent200StudentsItemGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateStudent200StudentsItemGender = {
    Male: 'Male',
    Female: 'Female',
} as const;
