/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

export type UpdateParent200Type = (typeof UpdateParent200Type)[keyof typeof UpdateParent200Type];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateParent200Type = {
    admin: 'admin',
    parent: 'parent',
} as const;
