/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { UpdateStudent200StudentsItem } from './updateStudent200StudentsItem';
import type { UpdateStudent200Type } from './updateStudent200Type';

export type UpdateStudent200 = {
    email: string;
    id: string;
    name: string;
    pamId?: string;
    password: string;
    phone: string;
    students: UpdateStudent200StudentsItem[];
    surname: string;
    type: UpdateStudent200Type;
};
