/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { UpdateStudent200StudentsItemGender } from './updateStudent200StudentsItemGender';

export type UpdateStudent200StudentsItem = {
    date_of_birth: string;
    gender: UpdateStudent200StudentsItemGender;
    grade: number;
    id: string;
    name: string;
    surname: string;
    teacher_id: string;
};
