/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { UpdateParent200StudentsItem } from './updateParent200StudentsItem';
import type { UpdateParent200Type } from './updateParent200Type';

export type UpdateParent200 = {
    email: string;
    id: string;
    name: string;
    password: string;
    phone: string;
    students: UpdateParent200StudentsItem[];
    surname: string;
    type: UpdateParent200Type;
};
