/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { UpdateParent200StudentsItemGender } from './updateParent200StudentsItemGender';

export type UpdateParent200StudentsItem = {
    date_of_birth: string;
    gender: UpdateParent200StudentsItemGender;
    grade: number;
    id: string;
    name: string;
    surname: string;
    teacher_id: string;
};
