/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */
import type { ReassessmentFromMedication } from './reassessmentFromMedication';
import type { ReassessmentToMedication } from './reassessmentToMedication';

export type UpgradeOrderParams = {
	key: string;
	email: string;
	medicationFrom: ReassessmentFromMedication;
	medicationTo: ReassessmentToMedication;
};
