/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */

export type UserGetResponseContactInfo = {
    email?: string;
    phone_number?: string;
};
