/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */
import type { UserPutRequestContactInfo } from './userPutRequestContactInfo';

export interface UserPutRequest {
    contact_info: UserPutRequestContactInfo;
    first_name?: string;
    surname?: string;
    user_name?: string;
    user_persona?: unknown;
    [key: string]: unknown;
}
