/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */

export type UserGetResponseType = (typeof UserGetResponseType)[keyof typeof UserGetResponseType];

 
export const UserGetResponseType = {
	whatsapp: 'whatsapp',
	api: 'api',
} as const;
