/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */

export type UserGetResponseType = (typeof UserGetResponseType)[keyof typeof UserGetResponseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserGetResponseType = {
    whatsapp: 'whatsapp',
    api: 'api',
} as const;
