/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * elliemd_api
 * OpenAPI spec version: 1.0
 */
import type { Wp } from './wp';

export interface User {
	dealerId: number;
	dob: string;
	email: string;
	firstName: string;
	gender: string;
	lastName: string;
	middleName?: string;
	phone: string;
	wp: Wp;
}
