/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */

export type VoiceflowResponseAnyOfType =
    (typeof VoiceflowResponseAnyOfType)[keyof typeof VoiceflowResponseAnyOfType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VoiceflowResponseAnyOfType = {
    path: 'path',
    end: 'end',
} as const;
