/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { VoiceflowResponseAnyOf } from './voiceflowResponseAnyOf';
import type { TextResponse } from './textResponse';
import type { ChoiceResponse } from './choiceResponse';
import type { LocationRequestResponse } from './locationRequestResponse';

export type VoiceflowResponse =
    | VoiceflowResponseAnyOf
    | TextResponse
    | ChoiceResponse
    | LocationRequestResponse;
