/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * school-manager-api
 * OpenAPI spec version: 1.0
 */
import type { PickEmbeddingExcludeKeyofEmbeddingId } from './pickEmbeddingExcludeKeyofEmbeddingId';

export type WebEmbedding = PickEmbeddingExcludeKeyofEmbeddingId;
