/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */

export type ListFilesParams = {
    tag?: string;
    /**
     * If you want to query a file for a different user, you can specify the user id here.
     */
    userId?: string;
};
