/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */

export type PickEmbeddingFileExcludeKeyofEmbeddingFileTextOrUserIdStatus =
    (typeof PickEmbeddingFileExcludeKeyofEmbeddingFileTextOrUserIdStatus)[keyof typeof PickEmbeddingFileExcludeKeyofEmbeddingFileTextOrUserIdStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PickEmbeddingFileExcludeKeyofEmbeddingFileTextOrUserIdStatus = {
    uploaded: 'uploaded',
    embedding: 'embedding',
    embedded: 'embedded',
    error: 'error',
    deleted: 'deleted',
    expired: 'expired',
} as const;
