/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * pam-ai-whatsapp
 * OpenAPI spec version: 1.0.0
 */
import type { UserGetResponseContactInfo } from './userGetResponseContactInfo';
import type { ObjectId } from './objectId';
import type { UserGetResponseType } from './userGetResponseType';

export interface UserGetResponse {
    contact_info: UserGetResponseContactInfo;
    first_name?: string;
    id: ObjectId;
    is_admin: boolean;
    parent_id?: ObjectId;
    surname?: string;
    type: UserGetResponseType;
    user_name?: string;
    user_persona?: unknown;
    [key: string]: unknown;
}
